// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRTWEAKPLAYERCONTROLS_HPP
#define _SLDRTWEAKPLAYERCONTROLS_HPP

#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Network/CBBASupport.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrControlCommands.hpp"
#include "rstl/string.hpp"

struct SLdrRevolutionPhysicalControl {
  SLdrRevolutionPhysicalControl();
  ~SLdrRevolutionPhysicalControl();

  int physicalControl; // 0x60d66244
};

void LoadTypedefRevolutionPhysicalControl(SLdrRevolutionPhysicalControl& data, CInputStream& input);

struct SLdrRevolutionControl {
  SLdrRevolutionControl();
  ~SLdrRevolutionControl();

  SLdrControlCommands commandEnum;                // 0xb0d17d4d
  int revolutionControlType;                      // 0x81cc3d3e
  SLdrRevolutionPhysicalControl physicalControl;  // 0xe646d3b7
  int physicalControlBoolean;                     // 0x6e14bc06
  SLdrRevolutionPhysicalControl physicalControl2; // 0xf0bf68a4
  int revolutionVirtualControl;                   // 0xfe819ddb
  int revolutionVirtualMenu;                      // 0x8d12458e
};

void LoadTypedefRevolutionControl(SLdrRevolutionControl& data, CInputStream& input);

struct SLdrPlayerMovementControls {
  SLdrPlayerMovementControls();
  ~SLdrPlayerMovementControls();

  SLdrRevolutionControl forward;     // 0x04124a09
  SLdrRevolutionControl backward;    // 0xade0103b
  SLdrRevolutionControl turnLeft;    // 0x416d1cc1
  SLdrRevolutionControl turnRight;   // 0xe6aa24c0
  SLdrSpline turnControl;            // 0xfb9117c0
  SLdrSpline lookUpTurnControl;      // 0x4058d24a
  SLdrSpline lookDownTurnControl;    // 0x466568f7
  SLdrRevolutionControl strafeLeft;  // 0x7adf18cd
  SLdrRevolutionControl strafeRight; // 0xef27daef
  SLdrRevolutionControl jump;        // 0x6b6fce63
};

void LoadTypedefPlayerMovementControls(SLdrPlayerMovementControls& data, CInputStream& input);

struct SLdrPlayerWeaponControls {
  SLdrPlayerWeaponControls();
  ~SLdrPlayerWeaponControls();

  SLdrRevolutionControl fireBeam;     // 0x82168860
  SLdrRevolutionControl autoFireBeam; // 0xd55c24c4
  SLdrRevolutionControl chargeBeam;   // 0x6fe93d70
  SLdrRevolutionControl fireMissile;  // 0xcbb88cb7
  SLdrRevolutionControl fireSeeker;   // 0x711804a6
  SLdrRevolutionControl hyperMode;    // 0xfad9340e
  SLdrSpline aimUpControl;            // 0x002f1e9d
  SLdrSpline aimDownControl;          // 0xfad945be
  SLdrSpline aimLeftControl;          // 0xa166125c
  SLdrSpline aimRightControl;         // 0xdf87aa4e
  SLdrSpline viewLockAimUpControl;    // 0x1a86616e
  SLdrSpline viewLockAimDownControl;  // 0x05f281c4
};

void LoadTypedefPlayerWeaponControls(SLdrPlayerWeaponControls& data, CInputStream& input);

struct SLdrPlayerMiscControls {
  SLdrPlayerMiscControls();
  ~SLdrPlayerMiscControls();

  SLdrRevolutionControl itemMenu;               // 0xddf88c92
  SLdrRevolutionControl useItem;                // 0x8b0e64f6
  SLdrRevolutionControl combatVisor;            // 0xd49e5fcf
  SLdrRevolutionControl scanVisor;              // 0x9c182689
  SLdrRevolutionControl xRayVisor;              // 0x011f0193
  SLdrRevolutionControl commandVisor;           // 0xbb560ad3
  SLdrRevolutionControl cycleVisorUp;           // 0x12a3619e
  SLdrRevolutionControl cycleVisorDown;         // 0x33e1a595
  SLdrRevolutionControl orbitLock;              // 0x23717b97
  SLdrRevolutionControl grappleLock;            // 0x0e59d622
  SLdrRevolutionControl grapplePull;            // 0x67d45eb2
  SLdrRevolutionControl summonShip;             // 0x7ee3acdf
  SLdrRevolutionControl dismissShip;            // 0x7e349bd0
  SLdrRevolutionControl shipFire;               // 0xf6c87bf5
  SLdrRevolutionControl shipPickUpItem;         // 0x8a2c06e4
  SLdrRevolutionControl shipDropItem;           // 0x1f2bc2af
  SLdrRevolutionControl scanItem;               // 0x4a88a76f
  SLdrRevolutionControl startContextualAction;  // 0xf3a2fbdd
  SLdrRevolutionControl cancelContextualAction; // 0x30d313eb
};

void LoadTypedefPlayerMiscControls(SLdrPlayerMiscControls& data, CInputStream& input);

struct SLdrBallMovementControls {
  SLdrBallMovementControls();
  ~SLdrBallMovementControls();

  SLdrRevolutionControl rollForward;  // 0xb4f29640
  SLdrRevolutionControl rollBackward; // 0xa25009d3
  SLdrRevolutionControl rollLeft;     // 0x9cba817b
  SLdrRevolutionControl rollRight;    // 0xcdc3a9cf
  SLdrRevolutionControl boostBall;    // 0x2f0e0276
  SLdrRevolutionControl spiderBall;   // 0x9a973454
  SLdrRevolutionControl screwAttack;  // 0x8b9f60a3
};

void LoadTypedefBallMovementControls(SLdrBallMovementControls& data, CInputStream& input);

struct SLdrBallMiscControls {
  SLdrBallMiscControls();
  ~SLdrBallMiscControls();

  SLdrRevolutionControl bomb;           // 0xd239fb95
  SLdrRevolutionControl morphIntoBall;  // 0x5880ba62
  SLdrRevolutionControl morphOutOfBall; // 0xa14f91f1
};

void LoadTypedefBallMiscControls(SLdrBallMiscControls& data, CInputStream& input);

struct SLdrCameraControls {
  SLdrCameraControls();
  ~SLdrCameraControls();

  SLdrRevolutionControl lookUp;         // 0x1c1d6f49
  SLdrRevolutionControl lookDown;       // 0x1a20d5f4
  SLdrRevolutionControl lookLeft;       // 0x90415e79
  SLdrRevolutionControl lookRight;      // 0x23c1333c
  SLdrRevolutionControl reorientCamera; // 0x2b4ba1a3
  SLdrRevolutionControl viewLock;       // 0xd47f24d7
  SLdrSpline lookUpControl;             // 0xa03390a5
  SLdrSpline lookDownControl;           // 0xe746f77e
};

void LoadTypedefCameraControls(SLdrCameraControls& data, CInputStream& input);

struct SLdrMapControls {
  SLdrMapControls();
  ~SLdrMapControls();

  SLdrRevolutionControl mapScreen;       // 0xfed78da3
  SLdrRevolutionControl mapCircleUp;     // 0x74e647c1
  SLdrRevolutionControl mapCircleDown;   // 0xdccf07b6
  SLdrRevolutionControl mapCircleLeft;   // 0x56ae8c3b
  SLdrRevolutionControl mapCircleRight;  // 0xbbd5fc52
  SLdrRevolutionControl mapMoveForward;  // 0x827c4e63
  SLdrRevolutionControl mapMoveBackward; // 0x0001f679
  SLdrRevolutionControl mapMoveLeft;     // 0xfb5628fa
  SLdrRevolutionControl mapMoveRight;    // 0x571bf6d0
  SLdrRevolutionControl mapZoomIn;       // 0x385cbd2f
  SLdrRevolutionControl mapZoomOut;      // 0x5f55ccca
};

void LoadTypedefMapControls(SLdrMapControls& data, CInputStream& input);

struct SLdrInventoryControls {
  SLdrInventoryControls();
  ~SLdrInventoryControls();

  SLdrRevolutionControl inventoryScreen; // 0x340f912e
  SLdrRevolutionControl menuUp;          // 0x769909c1
  SLdrRevolutionControl menuDown;        // 0x4dab695e
  SLdrRevolutionControl menuLeft;        // 0xc7cae2d3
  SLdrRevolutionControl menuRight;       // 0x1595f276
};

void LoadTypedefInventoryControls(SLdrInventoryControls& data, CInputStream& input);

struct SLdrMiscControls {
  SLdrMiscControls();
  ~SLdrMiscControls();

  SLdrMapControls map;                 // 0x9acb4ace
  SLdrInventoryControls inventory;     // 0xed3482b7
  SLdrRevolutionControl optionsScreen; // 0x36e52f14
  SLdrRevolutionControl logScreen;     // 0x10699c6f
};

void LoadTypedefMiscControls(SLdrMiscControls& data, CInputStream& input);

struct SLdrDebugControls {
  SLdrDebugControls();
  ~SLdrDebugControls();

  SLdrRevolutionControl moveCamera;          // 0x38ed0ec3
  SLdrRevolutionControl moveCameraFast;      // 0xce9d8f9b
  SLdrRevolutionControl moveCameraForward;   // 0xcf8d32f4
  SLdrRevolutionControl moveCameraBackward;  // 0x6e2701e2
  SLdrRevolutionControl moveCameraRight;     // 0x233dfcb8
  SLdrRevolutionControl moveCameraLeft;      // 0x6c8eda79
  SLdrRevolutionControl turnCameraRight;     // 0x52739b7b
  SLdrRevolutionControl turnCameraLeft;      // 0x936c903d
  SLdrRevolutionControl pitchCameraUp;       // 0xf3e413f0
  SLdrRevolutionControl pitchCameraDown;     // 0x769412eb
  SLdrRevolutionControl toggleCamera;        // 0xce92be94
  SLdrRevolutionControl dropPlayer;          // 0xfc31e19e
  SLdrRevolutionControl menuStart;           // 0x0bfcb7a2
  SLdrRevolutionControl menuUp;              // 0x769909c1
  SLdrRevolutionControl menuDown;            // 0x4dab695e
  SLdrRevolutionControl menuLeft;            // 0xc7cae2d3
  SLdrRevolutionControl menuRight;           // 0x1595f276
  SLdrRevolutionControl menuSelect;          // 0xbf09b38b
  SLdrRevolutionControl menuBack;            // 0xbcbe70f0
  SLdrRevolutionControl menuIncrementValue;  // 0xd38203d7
  SLdrRevolutionControl menuDecrementValue;  // 0xed1235d3
  SLdrRevolutionControl menuValueMultiplier; // 0xc73501a3
  SLdrRevolutionControl restartLevel;        // 0xc578ca0d
  SLdrRevolutionControl mapTeleport;         // 0x8bb24630
};

void LoadTypedefDebugControls(SLdrDebugControls& data, CInputStream& input);

struct SLdrPlayerControls {
  SLdrPlayerControls();
  ~SLdrPlayerControls();

  SLdrPlayerMovementControls firstPersonMovement; // 0x4cf2b66e
  SLdrPlayerWeaponControls firstPersonWeapons;    // 0x478b6c20
  SLdrPlayerMiscControls firstPersonMisc;         // 0x49bd3f51
  int unknown_0x61fe67a1;                         // 0x61fe67a1
  SLdrBallMovementControls ballMovement;          // 0x1681d3e9
  SLdrBallMiscControls ballMisc;                  // 0x0265e569
  int unknown_0xd1777bf7;                         // 0xd1777bf7
  SLdrCameraControls camera;                      // 0x40e350ad
  SLdrMiscControls misc;                          // 0xbe77ded2
  SLdrDebugControls debug;                        // 0x47069911
};

void LoadTypedefPlayerControls(SLdrPlayerControls& data, CInputStream& input);

struct SLdrTweakPlayerControls {
  SLdrTweakPlayerControls();
  ~SLdrTweakPlayerControls();

  rstl::string instanceName;             // 0x7fda1466
  SLdrPlayerControls revolutionControls; // 0x71cfc8e2
  SLdrPlayerControls gamecubeControls;   // 0x79be9348
};

void LoadTypedefTweakPlayerControls(SLdrTweakPlayerControls& data, CInputStream& input);

#endif
