// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRLUASCRIPT_HPP
#define _SLDRLUASCRIPT_HPP

#include "Kyoto/Network/CBBASupport.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "rstl/string.hpp"

struct SLdrLUAScript {
  SLdrLUAScript();
  ~SLdrLUAScript();

  SLdrEditorProperties editorProperties; // 0x255a4580
  rstl::string unknown_0xed4a2787;       // 0xed4a2787
  rstl::string unknown_0x9facea01;       // 0x9facea01
  rstl::string unknown_0xea46b664;       // 0xea46b664
  rstl::string unknown_0xa1ecc54b;       // 0xa1ecc54b
};

inline SLdrLUAScript::SLdrLUAScript()
: editorProperties()
, unknown_0xed4a2787()
, unknown_0x9facea01()
, unknown_0xea46b664()
, unknown_0xa1ecc54b() {
  editorProperties.unknown_0x5d298a43 = 3;
}

inline SLdrLUAScript::~SLdrLUAScript() {}

#endif
