// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRPLATFORMMOTIONPROPERTIES_HPP
#define _SLDRPLATFORMMOTIONPROPERTIES_HPP

#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Network/CBBASupport.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrSplineType.hpp"

struct SLdrPlatformMotionProperties {
  SLdrPlatformMotionProperties();
  ~SLdrPlatformMotionProperties();

  SLdrSplineType motionSplineType; // 0x493d6a2d
  SLdrSpline motionControlSpline;  // 0x27e5f874
  float motionSplineDuration;      // 0xfd1e2f56
  float initialTime;               // 0xa5753d52
  uint motionFlagsPlatformMotion;  // 0xae80628f
  SLdrSpline rollControlSpline;    // 0x628bdf0f
  SLdrSpline yawControlSpline;     // 0x78d03a32
  SLdrSpline pitchControlSpline;   // 0xb4a2e15a
};

void LoadTypedefPlatformMotionProperties(SLdrPlatformMotionProperties& data, CInputStream& input);

#endif
