// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCONTROLCOMMANDS_HPP
#define _SLDRCONTROLCOMMANDS_HPP

#include "Kyoto/Network/CBBASupport.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrControlCommands {
  SLdrControlCommands();
  ~SLdrControlCommands();

  int command; // 0x418b3422
};

void LoadTypedefControlCommands(SLdrControlCommands& data, CInputStream& input);

#endif
