// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRMOTIONINTERPOLATIONMETHOD_HPP
#define _SLDRMOTIONINTERPOLATIONMETHOD_HPP

#include "Kyoto/Network/CBBASupport.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrInterpolationMethod.hpp"

struct SLdrPathType {
  SLdrPathType();
  ~SLdrPathType();

  int curvature; // 0xf4ac7caa
};

void LoadTypedefPathType(SLdrPathType& data, CInputStream& input);

struct SLdrPathInterpolation {
  SLdrPathInterpolation();
  ~SLdrPathInterpolation();

  SLdrPathType pathShape; // 0x7fcd6908
};

void LoadTypedefPathInterpolation(SLdrPathInterpolation& data, CInputStream& input);

struct SLdrMotionInterpolationMethod {
  SLdrMotionInterpolationMethod();
  ~SLdrMotionInterpolationMethod();

  int motionType;                        // 0x948af571
  SLdrPathInterpolation path;            // 0x79de4ba5
  SLdrInterpolationMethod motionControl; // 0x287f9f45
};

void LoadTypedefMotionInterpolationMethod(SLdrMotionInterpolationMethod& data, CInputStream& input);

#endif
