// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCAMERASHAKERDATA_HPP
#define _SLDRCAMERASHAKERDATA_HPP

#include "Kyoto/CAssetId.hpp"
#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Network/CBBASupport.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrCameraShakerEnvelope {
  SLdrCameraShakerEnvelope();
  ~SLdrCameraShakerEnvelope();

  int shakeShape;       // 0xc6089a3f
  SLdrSpline amplitude; // 0x90b3cc7e
  SLdrSpline period;    // 0x69a81517
};

void LoadTypedefCameraShakerEnvelope(SLdrCameraShakerEnvelope& data, CInputStream& input);

struct SLdrCameraShakerData {
  SLdrCameraShakerData();
  ~SLdrCameraShakerData();

  uint flagsCameraShaker;                    // 0xc3e75c5f
  float attenuationDistance;                 // 0x4d283ac5
  float duration;                            // 0x8b51e23f
  CAssetId audioEffect;                    // 0xc2acb79e
  SLdrCameraShakerEnvelope horizontalMotion; // 0xd9eb71e0
  SLdrCameraShakerEnvelope verticalMotion;   // 0xc5b09632
  SLdrCameraShakerEnvelope forwardMotion;    // 0x21b704e3
};

void LoadTypedefCameraShakerData(SLdrCameraShakerData& data, CInputStream& input);

#endif
