// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRCONVERGENCE_HPP
#define _SLDRCONVERGENCE_HPP

#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Network/CBBASupport.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrVelocityConvergence {
  SLdrVelocityConvergence();
  ~SLdrVelocityConvergence();

  float maxSpeed;       // 0x82db0cbe
  float acceleration;   // 0x39fb7978
  float dampeningRange; // 0x1a111725
};

void LoadTypedefVelocityConvergence(SLdrVelocityConvergence& data, CInputStream& input);

struct SLdrSpringConvergence {
  SLdrSpringConvergence();
  ~SLdrSpringConvergence();

  bool criticallyDampened; // 0x6fa2f8bc
  float springConstant;    // 0xb3823863
  float dampenConstant;    // 0xb122a18d
  float threshold;         // 0x8e1b83f9
  float springMax;         // 0xacb1cdcb
  float tardis;            // 0x74d11538
};

void LoadTypedefSpringConvergence(SLdrSpringConvergence& data, CInputStream& input);

struct SLdrPIDConvergence {
  SLdrPIDConvergence();
  ~SLdrPIDConvergence();

  int pIDType; // 0xd0810123
  float kP;    // 0xe82b99e1
  float kI;    // 0xccf2cab2
  float kD;    // 0x706cd96c
};

void LoadTypedefPIDConvergence(SLdrPIDConvergence& data, CInputStream& input);

struct SLdrProportionalConvergence {
  SLdrProportionalConvergence();
  ~SLdrProportionalConvergence();

  float velocity;              // 0x02f01683
  SLdrSpline dampeningControl; // 0xf7fba2bf
};

void LoadTypedefProportionalConvergence(SLdrProportionalConvergence& data, CInputStream& input);

struct SLdrConvergence {
  SLdrConvergence();
  ~SLdrConvergence();

  int convergenceType;                      // 0x2ef22401
  SLdrVelocityConvergence velocity;         // 0x6f9d9b33
  SLdrSpringConvergence spring;             // 0x0cf33816
  SLdrPIDConvergence pID;                   // 0xf9e402ef
  SLdrProportionalConvergence proportional; // 0x085648bc
};

void LoadTypedefConvergence(SLdrConvergence& data, CInputStream& input);

#endif
