// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSPLINETYPE_HPP
#define _SLDRSPLINETYPE_HPP

#include "Kyoto/Network/CBBASupport.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrSplineType {
  SLdrSplineType();
  ~SLdrSplineType();

  int type; // 0xf53dcdd6
};

void LoadTypedefSplineType(SLdrSplineType& data, CInputStream& input);

#endif
