// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRINTERPOLATIONMETHOD_HPP
#define _SLDRINTERPOLATIONMETHOD_HPP

#include "Kyoto/Math/CMayaSpline.hpp"
#include "Kyoto/Network/CBBASupport.hpp"
#include "Kyoto/Streams/CInputStream.hpp"

struct SLdrInterpolationMethod {
  SLdrInterpolationMethod();
  ~SLdrInterpolationMethod();

  int interpolationControlType; // 0x09b5957d
  SLdrSpline controlSpline; // 0x15567fe7
  float easeIn; // 0xb08d3237
  float easeOut; // 0x67e3836a
  float duration; // 0x8b51e23f
};

void LoadTypedefInterpolationMethod(SLdrInterpolationMethod& data, CInputStream& input);

#endif
